filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
          
        - condition:
            or:
                
              - equals.docker.container.name: identity-service
                
              - equals.docker.container.name: assets-service
          
              - equals.docker.container.name: device-key-store
                
              - equals.docker.container.name: otd-service
              
              - equals.docker.container.name: mngtclient

              - equals.docker.container.name: groupsandpolicies
                
          config:
            - type: container       
              containers.ids:
                - "${data.docker.container.id}"       
              multiline.pattern: '^[crit|fail|warn|info|dbug|trce]'
              multiline.negate: true
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              multiline.match: after
              fields:
                application: "${data.docker.container.name}"
              
filebeat.inputs:
                                                                   
- type: log
  enabled: true
  paths:
  - /var/log/rabbitmq/rabbitmq.log
                                          
                         
                 
    
                 
            
                            
                          
                          
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
                                      
             
                      
                      
                                    
  multiline.match: after
  fields:
    application: rabbit-mq

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'http://elasticsearch:9200'
  username: 'nolucksec'
  password: 'noluckSec!'
  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after
  
                                        
            
    
                         
setup.ilm.enabled: false

logging.level: warning
