global: 
  scrape_interval: 10s
scrape_configs:
  - job_name: container-monitoring
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: machine-monitoring
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: [ 'pushgateway:9091' ]
        labels:
          pushgateway_instance: container_status