{
 "title": "Kubernetes / Compute Resources / Namespace (Pods)11111111111111111111",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods - Up To Date",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"default\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Pods restart in 30m",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m]))"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}